repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: bash -c "cd Proyecto/Backend && gofmt -l -w ."
        language: system
        types: [go]

      - id: go-vet
        name: go vet
        entry: bash -c "cd Proyecto/Backend && go vet ./..."
        language: system
        types: [go]

      - id: go-test
        name: go test
        entry: bash -c "cd Proyecto/Backend && go test ./..."
        language: system
        pass_filenames: false
